# Generated by Django 4.0.3 on 2022-04-05 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
