# Generated by Django 4.0.3 on 2022-04-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0002_remove_track_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.AddField(
            model_name='album',
            name='user_name',
            field=models.CharField(default='no author', max_length=50),
        ),
    ]
