# Generated by Django 4.0.3 on 2022-04-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0009_alter_playlist_cover_likedsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedsongs',
            name='tracks',
        ),
    ]
