# Generated by Django 4.0.3 on 2022-04-30 10:26

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0011_alter_album_cover_alter_playlist_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('cover', models.ImageField(blank=True, default='default\\default-cover.png', null=True, upload_to=base.services.get_path_upload_social_links, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), base.services.validate_size_image])),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='user_name',
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, default='default\\default-user-image.png', null=True, upload_to=base.services.get_path_upload_artist, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), base.services.validate_size_image])),
                ('social_links', models.ManyToManyField(blank=True, null=True, related_name='social_links', to='audio_library.sociallinks')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(related_name='author', to='audio_library.artist'),
        ),
    ]
