# Generated by Django 4.0.3 on 2022-05-11 11:24

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0012_sociallinks_remove_album_user_name_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, default='default\\default-user-image.png', null=True, upload_to=base.services.get_path_upload_artist, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), base.services.validate_size_image]),
        ),
    ]
