# Generated by Django 4.0.3 on 2022-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0013_alter_artist_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='cover',
        ),
    ]
