# Generated by Django 4.0.3 on 2022-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0014_remove_sociallinks_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.JSONField(default={'Liked songs': False}),
        ),
    ]
