# Generated by Django 4.0.3 on 2022-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0015_track_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='track_genres', to='audio_library.genre'),
        ),
    ]
