# Generated by Django 4.0.3 on 2022-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0017_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='plays_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
